# Generated by Django 4.2.24 on 2025-12-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_rating',
            field=models.IntegerField(choices=[(0, 'G'), (1, 'PG'), (2, 'PG-13'), (3, 'R')], default=0),
        ),
    ]
